name: Deploy FastAPI to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set Up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Install gke-gcloud-auth-plugin
      run: |
        ARCH=$(uname -m)
        if [[ "$ARCH" == "x86_64" ]]; then
          curl -sSL https://github.com/google-cloud-sdk/gke-gcloud-auth-plugin/releases/download/v0.0.1/gke-gcloud-auth-plugin-linux-amd64 -o /usr/local/bin/gke-gcloud-auth-plugin
        elif [[ "$ARCH" == "aarch64" ]]; then
          curl -sSL https://github.com/google-cloud-sdk/gke-gcloud-auth-plugin/releases/download/v0.0.1/gke-gcloud-auth-plugin-linux-arm64 -o /usr/local/bin/gke-gcloud-auth-plugin
        else
          echo "Unsupported architecture: $ARCH"
          exit 1
        fi
        chmod +x /usr/local/bin/gke-gcloud-auth-plugin

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-app:$GITHUB_SHA .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/fastapi-repo/fastapi-app:$GITHUB_SHA

    - name: Authenticate kubectl with GKE
      run: |
        gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/hpa.yaml --validate=false
        kubectl apply -f k8s/service.yaml --validate=false
